---
lan_interface: eth0
wan_interface: eth1
zerotier_ip_address: "172.26.115.180/20"

zerotier_download_base_url: "https://download.zerotier.com"
zerotier_gpg_key_url: "https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg"
zerotier_apt_repository: "deb {{ zerotier_download_base_url }}/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"

zerotier_network_id: ""
zerotier_leave: false

allow_managed: 0
allow_global: 0
allow_default: 0
allow_dns: 0

# Variables for installing bridge-utils
bridge_utils_package: bridge-utils

# Variables for copying Netplan configuration file
netplan_config_file_dest: /etc/netplan/50-cloud-init.yaml
