---
- name: Create directory path
  ansible.builtin.file:
    path: "{{ softether_vpnserver_path }}/config"
    state: directory
    mode: 0755
  tags: install, server

- name: Touch lang.config
  ansible.builtin.copy:
    content: ""
    dest: "{{ softether_vpnserver_path }}/config/lang.config"
    group: root
    owner: root
    mode: 0644
  tags: install, server

- name: Touch vpn_server.config
  ansible.builtin.copy:
    content: ""
    dest: "{{ softether_vpnserver_path }}/config/vpn_server.config"
    group: root
    owner: root
    mode: 0644
  tags: install, server

- name: Deploying docker-compose for softether-vpnserver
  ansible.builtin.template:
    src: docker-compose.yml.server
    dest: "{{ softether_vpnserver_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags: install, server

- name: Launch docker-compose softether-vpnserver service
  community.docker.docker_compose:
    project_src: "{{ softether_vpnserver_path }}"
    state: present
    build: false
    pull: true
  tags: install, server

- name: Adding alias for vpncmd
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "alias vpncmd='docker exec -it softether-vpnserver /usr/local/libexec/softether/vpncmd/vpncmd'"
    owner: root
    regexp: "^alias vpncmd='docker exec -it softether-vpnserver /usr/local/libexec/softether/vpncmd/vpncmd'$"
    state: present
    insertafter: EOF
    create: True
  tags: config, server

- name: Enabling remote access
  ansible.builtin.shell: |
    docker exec -it softether-vpnserver \
      /usr/local/libexec/softether/vpncmd/vpncmd \
        localhost /server /cmd RemoteEnable
  tags: config, server
